### ISSUE TITLE
Calendar should show the date time options. 

### ISSUE THREAD

**Issue by pankaj-ag** [ColoredCow/employee-portal#587] opened 2018-07-16 09:31 UTC
When we update the round of any volunteer the calendar should show the options for a time also. Currently, we do that manually. 

![image](https://user-images.githubusercontent.com/10670690/42751348-1bc01c96-8908-11e8-9e98-ac0d91a687f5.png)

**Comment by rathorevaibhav** [comment] 2018-07-17 11:14
Duplicate of #461

**Closed by rathorevaibhav** 2018-07-17 11:14 UTC
Labels: good first issue
